### ISSUE TITLE
doc wrong

### ISSUE THREAD

**Issue by XingyuZhang2018** [under-Peter/OMEinsum.jl#108]
https://github.com/under-Peter/OMEinsum.jl/blob/30b2de9b9f6d188fb21c139d2cccc4751592aef6/src/autodiff.jl#L20

MethodError: no method matching einsum_grad(::EinCode{(('i', 'j'), ('j', 'k')), ('i', 'k')}, ::Tuple{Matrix{Float64}, Matrix{Float64}}, ::Tuple{Char, Char}, ::IndexSize{4, Char}, ::Matrix{Float64}, ::Int64)

**Comment by GiggleLiu** [comment]
Hi, thanks for the issue, can you please check wheter you are using the correct version?
```julia
julia> using OMEinsum

julia> using OMEinsum: einsum_grad, get_size_dict

julia> a, b = rand(2,2), rand(2,2);

julia> c = einsum(EinCode((('i','j'),('j','k')), ('i','k')), (a,b));

julia> sd = get_size_dict((('i','j'),('j','k')), (a,b));

julia> einsum_grad((('i','j'),('j','k')), (a,b), ('i','k'), sd, c, 1) ≈ c * transpose(b)
true
```

```julia pkg
(@v1.6) pkg> st OMEinsum
      Status `~/.julia/environments/v1.6/Project.toml`
  [ebe7aa44] OMEinsum v0.4.2

(@v1.6) pkg> 
```

**Comment by XingyuZhang2018** [comment]
`[e88e6eb3] Zygote v0.6.8`

**Comment by XingyuZhang2018** [comment]
[ebe7aa44] OMEinsum v0.3.3

**Comment by GiggleLiu** [comment]
Then I think you need to upgrade your OMEinsum to see if this problem still exists.

**Comment by XingyuZhang2018** [comment]
Some other packages are depended OMEinsum v0.3.3, so I go to v0.3.3's doc, and everything is right. Thank you for reminding me the version difference.
