### ISSUE TITLE
Suppress "OMEinsum: YOU FIND CUDA!" message

### ISSUE THREAD

**Issue by nmoran** [under-Peter/OMEinsum.jl#114]
If CUDA.jl is imported when OMEinsum is imported the above message is printed to stdout. This has lead to some confusion since this can happen even on systems where there are no GPUs (since CUDA.jl is safe to install on such systems to enable a check for GPU presence). Could be useful to remove this message or change to an info log message instead.

**Comment by GiggleLiu** [comment]
I would prefer changing it to a log message. Because the CUDA is optionally imported by Requires, if you do not use CUDA, it does not load the CUDA functionality. This is an important message to tell user the CUDA functionality is loaded correctly.

How do you like
```julia
julia> @info "OMEinsum loaded the CUDA module"
[ Info: OMEinsum loaded the CUDA module
```

**Comment by nmoran** [comment]
Yes that would be better and would be easier to suppress this output by changing the logger properties. Wonder if it would be a bad idea to switch to using `CUDA.functional(true)` instead of Requires (see https://cuda.juliagpu.org/dev/installation/conditional/)?

**Comment by GiggleLiu** [comment]
I guess that will increase the using time? Current using time of OMEinsum is much smaller than CUDA.
```julia
julia> @time using OMEinsum
  0.476703 seconds (990.38 k allocations: 53.562 MiB, 2.76% gc time)
```

**Comment by nmoran** [comment]
Yes that's a very good point and a good reason to stick with using Requires. CUDA is significantly slower even when no GPU is present.
