### ISSUE TITLE
use faster tensor contraction for CuArrays (BLAS number types)

### ISSUE THREAD

**Issue by GiggleLiu** [under-Peter/OMEinsum.jl#133]
The `permutedims` is very slow, much slower than the one in pytorch, see
1. The CUDA.jl wrapper https://github.com/JuliaGPU/CUDA.jl/blob/303d4ffff93469babbdf68bf5be38a8e6698ee8e/lib/cutensor/wrappers.jl

2. The pytorch implementation: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Linear.cpp#L631

We should consider using `permutation!` in CUTENSOR.

**Comment by GiggleLiu** [comment]
Note:

```python
In [26]: timeit t.permute(tuple(torch.randperm(26))); torch.cuda.synchronize()
66.5 µs ± 132 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

Much faster than the one in #132

**Comment by IvanYashchuk** [comment]
Here's PyTorch implementation of `torch.permute`:
https://github.com/pytorch/pytorch/blob/b7b32b56f129b70782eb3acf02a966605f5b1209/aten/src/ATen/native/TensorShape.cpp#L927-L945

It permutes the shape and strides and creates a new tensor with the same data (`torch.Storage`) but with a new shape&stride.

The link in the issue description is for `torch.tensordot`.

**Comment by GiggleLiu** [comment]
Thanks for the links to the pytorch implementation @IvanYashchuk .
@kshyatt I find current overhead of `permutedims` is still very noticeable when time complexity and space complexity are close, e.g. in one of my application, it is 1/3. It is even worse for regular element types I can imagine. Here is my plan to fix the problem,

* [ ] modify the compilation of binary rules in OMEinsum: https://github.com/under-Peter/OMEinsum.jl/blob/d5e22314eec16a6b8f59d9facb497fa9a7f15a0f/src/binaryrules.jl#L219
* [ ] port these two function for BLAS number types: https://github.com/JuliaGPU/CUDA.jl/blob/7778e34320df228d005b766521b77a24dc4b3361/lib/cutensor/interfaces.jl#L39 and https://github.com/JuliaGPU/CUDA.jl/blob/303d4ffff93469babbdf68bf5be38a8e6698ee8e/lib/cutensor/wrappers.jl#L206
* [ ] make current implementation of `permutedims` in `OMEinsum` the fallback in `CUDA.jl` because it is faster and does not unroll the permutation order.

**Comment by GiggleLiu** [comment]
The CUTENSOR `permutedims` is not as fast as expected, it is even slower than the naive generic implementation... even for the inplace version (tested on V100).

```julia
julia> using Random

julia> using CUDA.CUTENSOR

julia> using CUDA

julia> a = CUDA.rand(Float32, fill(2, 26)...);

julia> pm = randperm(26);

julia> Array(permutedims(a, pm)) ≈ Array(CUTENSOR.permutation!(1f0, a, collect(1:ndims(a)), zero(a), pm))
true

julia> using BenchmarkTools

julia> @benchmark CUDA.@sync permutedims($a, $pm)
BenchmarkTools.Trial: 179 samples with 1 evaluation.
 Range (min … max):  19.886 ms … 503.220 ms  ┊ GC (min … max): 0.00% … 0.45%
 Time  (median):     20.039 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   28.305 ms ±  59.219 ms  ┊ GC (mean ± σ):  0.13% ± 0.06%

  █                                                             
  █▁▁▁▁▁▁▁▁▁▁▁▄▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▄ ▄
  19.9 ms       Histogram: log(frequency) by time       464 ms <

 Memory estimate: 2.61 KiB, allocs estimate: 33.

julia> @benchmark CUDA.@sync CUTENSOR.permutation!(1f0, $a, collect(1:ndims($a)), $(zero(a)), $pm)
BenchmarkTools.Trial: 213 samples with 1 evaluation.
 Range (min … max):  23.357 ms … 23.649 ms  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     23.459 ms              ┊ GC (median):    0.00%
 Time  (mean ± σ):   23.467 ms ± 58.847 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

               ▃ ▁█▁▁▆▁     ▆ ▁                                
  ▅▆▄▅▄▄▅▄▃██▇▄█▆███████▇██▇█▅██▇▅▇▄▅▆▇▅▃▃▁▄▄▁▁▄▃▃▄▃▃▁▁▃▁▁▃▁▃ ▄
  23.4 ms         Histogram: frequency by time        23.6 ms <

 Memory estimate: 4.58 KiB, allocs estimate: 33.

julia> using OMEinsum
[ Info: OMEinsum loaded the CUDA module successfully

julia> @benchmark CUDA.@sync permutedims($a, $pm)
BenchmarkTools.Trial: 242 samples with 1 evaluation.
 Range (min … max):  11.991 ms … 491.690 ms  ┊ GC (min … max): 0.00% … 0.52%
 Time  (median):     12.170 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   20.638 ms ±  61.719 ms  ┊ GC (mean ± σ):  0.20% ± 0.07%

  █                                                             
  █▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▄▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▅ ▅
  12 ms         Histogram: log(frequency) by time       491 ms <

 Memory estimate: 4.56 KiB, allocs estimate: 72.
```

**Comment by GiggleLiu** [comment]
The performance of `CUTENSOR.contraction!` is even worse
```julia
julia> s = CUDA.randn(2,2,2);

julia> o = CUDA.zeros(fill(2, 25)...);

julia> ainds = collect(1:26);

julia> sinds = [13, 27, 9]
3-element Vector{Int64}:
 13
 27
  9

julia> oinds = (setdiff(ainds, sinds) ∪ setdiff(sinds, ainds))[randperm(25)];

julia> Array(CUTENSOR.contraction!(1f0, a, ainds, CUTENSOR.CUTENSOR_OP_IDENTITY, s, sinds, CUTENSOR.CUTENSOR_OP_IDENTITY, 0f0, o, oinds, CUTENSOR.CUTENSOR_OP_IDENTITY, CUTENSOR.CUTENSOR_OP_IDENTITY)) ≈ Array(EinCode([ainds, sinds], oinds)(a, s))
true

julia> @benchmark CUDA.@sync CUTENSOR.contraction!(1f0, $a, $ainds, CUTENSOR.CUTENSOR_OP_IDENTITY, $s, $sinds, CUTENSOR.CUTENSOR_OP_IDENTITY, 0f0, $o, $oinds, CUTENSOR.CUTENSOR_OP_IDENTITY, CUTENSOR.CUTENSOR_OP_IDENTITY)
BenchmarkTools.Trial: 80 samples with 1 evaluation.
 Range (min … max):  62.603 ms … 62.908 ms  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     62.753 ms              ┊ GC (median):    0.00%
 Time  (mean ± σ):   62.756 ms ± 69.343 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

           ▁        ▃     ▁▁  █   ▁ ▃  ▁      ▁   ▆ ▁          
  ▄▁▁▁▄▇▄▁▁█▄▁▁▄▁▁▄▇█▇▇▇▄▁██▇▇█▁▁▇█▇█▇▄█▁▄▄▄▇▁█▄▁▄█▇█▁▁▁▁▄▁▁▄ ▁
  62.6 ms         Histogram: frequency by time        62.9 ms <

 Memory estimate: 19.33 KiB, allocs estimate: 72.


julia> @benchmark CUDA.@sync $(EinCode([ainds, sinds], oinds))($a, $s)
BenchmarkTools.Trial: 146 samples with 1 evaluation.
 Range (min … max):  17.669 ms … 486.886 ms  ┊ GC (min … max): 0.00% … 0.57%
 Time  (median):     17.871 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   34.701 ms ±  85.701 ms  ┊ GC (mean ± σ):  0.27% ± 0.10%

  █                                                             
  █▁▁▁▁▁▁▁▁▁▁▁▁▁▄▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▇ ▄
  17.7 ms       Histogram: log(frequency) by time       487 ms <

 Memory estimate: 17.19 KiB, allocs estimate: 224.
```

**Comment by GiggleLiu** [comment]
As a comparison, the pytorch version is
```ipython
In [1]: import torch

In [2]: t = torch.zeros(*[2 for i in range(26)], dtype=torch.float32, device=torch.device("cuda:0"));

In [3]: b = torch.zeros(*[2 for i in range(3)], dtype=torch.float32, device=torch.device("cuda:0"));

In [4]: timeit torch.tensordot(t, b, dims=([7, 2], [1,0])); torch.cuda.synchronize()
3.08 ms ± 32.3 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by GiggleLiu** [comment]
@IvanYashchuk It seems pytorch does not use CUTENSOR because it is so much faster in tensor contraction, do you know how is its device code in pytorch implemented (does it uses some backend or has its own backend)?

**Comment by IvanYashchuk** [comment]
In Julia `permutedims` is a copy operation. To replicate PyTorch behavior `PermutedDimsArray` needs to be used (so that dimension permutation is a view). `PermutedDimsArray` seem to work with `CuArray`:
```julia
julia> s = CUDA.randn(2,2,2,2);
julia> strides(s)
(1, 2, 4, 8)
julia> strides(PermutedDimsArray(s, randperm(4)))
(1, 4, 2, 8)
```

```julia
julia> using Random

julia> using CUDA

julia> a = CUDA.rand(Float32, fill(2, 26)...);

julia> pm = randperm(26);

julia> using BenchmarkTools

julia> @benchmark CUDA.@sync PermutedDimsArray(a, pm)
BenchmarkTools.Trial: 10000 samples with 9 evaluations.
 Range (min … max):  2.078 μs … 204.956 μs  ┊ GC (min … max): 0.00% … 98.27%
 Time  (median):     2.278 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   2.341 μs ±   2.046 μs  ┊ GC (mean ± σ):  0.86% ±  0.98%

   █▄        ▁
  ▇██▅▃▂▇▆▄▅██▃▅▄▄▂▂▂▁▂▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁ ▂
  2.08 μs         Histogram: frequency by time        3.68 μs <

 Memory estimate: 816 bytes, allocs estimate: 5.
 
 julia> @benchmark CUDA.@sync CuArray(PermutedDimsArray(a, pm))
BenchmarkTools.Trial: 47 samples with 1 evaluation.
 Range (min … max):   79.809 ms … 210.045 ms  ┊ GC (min … max):  0.48% … 53.84%
 Time  (median):     104.378 ms               ┊ GC (median):    10.66%
 Time  (mean ± σ):   108.124 ms ±  19.444 ms  ┊ GC (mean ± σ):  13.96% ±  8.91%

            ▂█▂▁
  ▅▁▁▁▁▅▁▁▁▁████▅▅▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▅▁▁▁▁▁▁▁▁▁▁▁▁▅ ▁
  79.8 ms       Histogram: log(frequency) by time        210 ms <

 Memory estimate: 256.01 MiB, allocs estimate: 70.
```

So now we have permutation views, the next thing needed is fast reshaping. In PyTorch `tensordot` is implemented using reshaping inputs to 2D calling matrix multiplication and then reshaping to the result tensor shape, `einsum` is implemented using reshaping inputs to 3D and calling batched matrix multiplication ([source](https://github.com/pytorch/pytorch/blob/103fc5f9a5590d5b2fec6f7e89a1ab4f6e984fb4/aten/src/ATen/native/Linear.cpp#L106)). In PyTorch reshaping is a view for C-contiguous inputs and a copy otherwise.

In Julia `reshape` is a view and copy of reshaped `PermutedDimsArray(::CuArray)` is not implemented without scalar indexing:
```julia
julia> a = CUDA.rand(Float32, fill(2, 4)...);

julia> b = PermutedDimsArray(a, randperm(4));

julia> strides(b)
(8, 4, 1, 2)

julia> bb = reshape(b, (4, 4));

julia> CuArray(bb)
ERROR: Scalar indexing is disallowed.
```
Also `strides(::Base.ReshapedArray)` doesn't exist.

Here's PyTorch profiling of `tensordot` for the example from https://github.com/under-Peter/OMEinsum.jl/issues/133#issuecomment-1002350605, which shows that 98% of the time is spent doing 2D matmul and 2% is for reshaping, permutation, and reserving memory for the result:
```python
In [26]: import torch

In [27]: from torch.profiler import profile, record_function, ProfilerActivity

In [28]: t = torch.zeros(*[2 for i in range(26)], dtype=torch.float32, device=torch.device("cuda:0"));

In [29]: b = torch.zeros(*[2 for i in range(3)], dtype=torch.float32, device=torch.device("cuda:0"));

In [30]: with profile(activities=[
    ...:         ProfilerActivity.CPU, ProfilerActivity.CUDA], record_shapes=True) as prof:
    ...:     with record_function("tensordot"):
    ...:         torch.tensordot(t, b, dims=([7, 2], [1,0]));
    ...:

In [33]: print(prof.key_averages().table(sort_by="cuda_time_total"))
------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
                    Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg    # of Calls
------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
               tensordot         0.05%     296.000us        98.07%     645.061ms     645.061ms      84.000us         0.01%     647.974ms     647.974ms             1
         aten::tensordot         0.01%      59.000us        98.02%     644.757ms     644.757ms      36.000us         0.01%     647.886ms     647.886ms             1
                aten::mm        97.98%     644.440ms        97.98%     644.440ms     644.440ms     646.731ms        99.80%     646.731ms     646.731ms             1
           aten::reshape         0.00%      31.000us         0.03%     213.000us      71.000us      21.000us         0.00%       1.086ms     362.000us             3
             aten::clone         0.00%      28.000us         0.02%     134.000us      67.000us      29.000us         0.00%       1.054ms     527.000us             2
             aten::copy_         0.01%      65.000us         0.01%      65.000us      32.500us     998.000us         0.15%     998.000us     499.000us             2
           aten::permute         0.00%      27.000us         0.01%      45.000us      22.500us      24.000us         0.00%      33.000us      16.500us             2
        aten::empty_like         0.00%      18.000us         0.01%      41.000us      20.500us      13.000us         0.00%      27.000us      13.500us             2
             aten::zeros         1.93%      12.665ms         1.93%      12.690ms      12.690ms      17.000us         0.00%      21.000us      21.000us             1
             aten::empty         0.01%      48.000us         0.01%      48.000us      12.000us      19.000us         0.00%      19.000us       4.750us             4
      aten::_unsafe_view         0.00%      17.000us         0.00%      30.000us      15.000us       7.000us         0.00%      10.000us       5.000us             2
        aten::as_strided         0.00%      18.000us         0.00%      18.000us       9.000us       9.000us         0.00%       9.000us       4.500us             2
             aten::zero_         0.00%       8.000us         0.00%       8.000us       8.000us       3.000us         0.00%       3.000us       3.000us             1
              aten::view         0.00%      13.000us         0.00%      13.000us       6.500us       3.000us         0.00%       3.000us       1.500us             2
    aten::_reshape_alias         0.00%      18.000us         0.00%      18.000us      18.000us       1.000us         0.00%       1.000us       1.000us             1
------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 657.751ms
Self CUDA time total: 647.995ms
```

Maybe using more `PermutedDimsArray` instead of `permutedims` and doing copies only when really necessary would help the performance here.

**Comment by GiggleLiu** [comment]
@IvanYashchuk Thanks. I think the stride trick and reshaped view is clear. What I want to know is how bmm handle the views in the code you refered
https://github.com/pytorch/pytorch/blob/103fc5f9a5590d5b2fec6f7e89a1ab4f6e984fb4/aten/src/ATen/native/Linear.cpp#L106

This is the function handling the real computation.

**Comment by IvanYashchuk** [comment]
For non-contiguous arrays reshape is not a view in PyTorch, it always copies and returns a C-contiguous reshaped copy, and this copy is fast (I guess mainly due to using caching allocator). Does CUDA.jl use caching allocator, does it need to call cudaMalloc for each new CuArray?

bmm uses [`cublas<t>gemmStridedBatched()`](https://docs.nvidia.com/cuda/cublas/index.html#cublas-lt-t-gt-gemmstridedbatched) which allows specifying leading dimension stride (`lda, ldb, ldc`) and matrix stride (`strideA, strideB and strideC`), so it can work with strided view inputs without copies using strides info.

 In the case of `torch.einsum` input to bmm after reshape is always contiguous and most likely copied, because this is how reshape behaves in PyTorch.

**Comment by Fanerst** [comment]
Using NVIDIA A100-PCIE 80G with NVIDIA Driver Version 470.82.01 and CUDA Version 11.4, the test results are listed below.

```julia
julia> using OMEinsum, OMEinsumContractionOrders, Graphs
[ Info: Precompiling OMEinsumContractionOrders [6f22d1fd-8eed-4bb7-9776-e7d684900715]

julia> function random_regular_eincode(n, k; optimize=nothing)
            g = Graphs.random_regular_graph(n, k)
            ixs = [minmax(e.src,e.dst) for e in Graphs.edges(g)]
            return EinCode((ixs..., [(i,) for i in     Graphs.vertices(g)]...), ())
           end
random_regular_eincode (generic function with 1 method)

julia> code = random_regular_eincode(220, 3);

julia> optcode_tree = optimize_code(code, uniformsize(code, 2), TreeSA(sc_target=29, βs=0.1:0.1:20,
                                                                       ntrials=5, niters=30, sc_weight=2.0));

julia> timespace_complexity(optcode_tree, uniformsize(code, 2))
(33.17598124621909, 28.0)

julia> @benchmark CUDA.@sync optcode_tree([CUDA.rand(fill(2, length(ix))...) for ix in getixsv(optcode_tree)]...)
BenchmarkTools.Trial: 1 sample with 1 evaluation.
 Single result which took 23.021 s (0.00% GC) to evaluate,
 with a memory estimate of 2.88 MiB, over 49219 allocations.

julia> writejson("test.json", optcode_tree)
```

While for pytorch, with the test code and the same device
```python
import json
import torch
import time
from copy import deepcopy

eqs = []
allow_ascii = list(range(65, 90)) + list(range(97, 122))
device = 'cuda:0'

def read_tree(tree):
    if not tree['isleaf']:
        eqs.append((tree['eins']['ixs'], tree['eins']['iy']))
        for branch in tree['args']:
            read_tree(branch)

def list_duplicates_of(seq,item):
    start_at = -1
    locs = []
    while True:
        try:
            loc = seq.index(item,start_at+1)
        except ValueError:
            break
        else:
            locs.append(loc)
            start_at = loc
    return locs

def pytorch_einsum(tensors, order, einsum_eqs):
    assert len(order) == len(einsum_eqs)
    for i in range(len(order)):
        m, n = order[i]
        eq = einsum_eqs[i]
        tensors[m] = torch.einsum(eq, tensors[m], tensors[n])
    return tensors[m]

with open("test.json", 'r') as f:
    optcode = json.load(f)

inputs_eq = optcode['inputs']
tree = optcode['tree']
read_tree(tree)

einsum_eqs, order = [], []

inputs_eq_copy = deepcopy(inputs_eq)
for i in range(len(eqs)-1, -1, -1):
    bonds_i, bonds_j = eqs[i][0]
    bonds_result = eqs[i][1]
    if bonds_i != bonds_j:
        loc_a, loc_b = inputs_eq.index(bonds_i), inputs_eq.index(bonds_j)
    else:
        assert inputs_eq.count(bonds_i) == 2
        loc_a, loc_b = list_duplicates_of(inputs_eq, bonds_i)
    inputs_eq[loc_a] = bonds_result
    all_bonds = list(set(bonds_i) | set(bonds_j))
    eq_current = ''.join([chr(allow_ascii[all_bonds.index(bond)]) for bond in bonds_i]) + ',' + \
                 ''.join([chr(allow_ascii[all_bonds.index(bond)]) for bond in bonds_j]) + '->' + \
                 ''.join([chr(allow_ascii[all_bonds.index(bond)]) for bond in bonds_result])
    einsum_eqs.append(eq_current)
    order.append((loc_a, loc_b))

repeat_times = 10
torch.cuda.synchronize(device)
t0 = time.time()
for _ in range(repeat_times):
    tensors = [torch.rand((2,) * len(i), dtype=torch.float32, device=device) for i in inputs_eq_copy]
    pytorch_einsum(tensors, order, einsum_eqs)

torch.cuda.synchronize(device)
t1 = time.time()
print((t1 - t0) / repeat_times)
```
one will get the final contraction time `0.27354960441589354` seconds.

**Comment by GiggleLiu** [comment]
Thank you very much @Fanerst . It seems we should overhaul the contraction implementation of high dimensional tensors in `OMEinsum`. I collected your benchmarks here: https://github.com/TensorBFS/TensorNetworkBenchmarks to help people reproduce these benchmarks.

**Comment by GiggleLiu** [comment]
Ah, I just notice your benchmark only collects one sample, that time is probably dominated by the overhead. See this new timing on V100 device.

```julia
➜  scripts git:(master) ✗ JULIA_CUDA_USE_BINARYBUILDER=false julia benchmark_OMEinsum.jl
[ Info: OMEinsum loaded the CUDA module successfully
BenchmarkTools.Trial: 3 samples with 1 evaluation.
 Range (min … max):  1.705 s …    1.706 s  ┊ GC (min … max): 0.39% … 0.12%
 Time  (median):     1.705 s               ┊ GC (median):    0.38%
 Time  (mean ± σ):   1.705 s ± 788.800 μs  ┊ GC (mean ± σ):  0.29% ± 0.15%

  █              █                                         █  
  █▁▁▁▁▁▁▁▁▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█ ▁
  1.7 s          Histogram: frequency by time         1.71 s <

 Memory estimate: 3.06 MiB, allocs estimate: 53724.
```

Can you please run the benchmark script on your device again following the guide in this repo: https://github.com/TensorBFS/TensorNetworkBenchmarks?

**Comment by Fanerst** [comment]
@GiggleLiu 
I've reproduce the correct benchmark. Here is the result:
```julia
(base) panfeng@fatcat:~/dev/TensorNetworkBenchmarks/scripts$ JULIA_CUDA_USE_BINARYBUILDER=false julia benchmark_OMEinsum.jl
[ Info: OMEinsum loaded the CUDA module successfully
BenchmarkTools.Trial: 3 samples with 1 evaluation.
 Range (min … max):  998.483 ms …    1.228 s  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):        1.086 s               ┊ GC (median):    0.00%
 Time  (mean ± σ):      1.104 s ± 116.020 ms  ┊ GC (mean ± σ):  0.00% ± 0.00%

  █                      █                                    █
  █▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█ ▁
  998 ms           Histogram: frequency by time          1.23 s <

 Memory estimate: 2.98 MiB, allocs estimate: 51057.
```
with the exact version of packages you required.

**Comment by GiggleLiu** [comment]
Thanks, that makes sense. It is in the similar scale as difference in `tensordot` in pytorch and `permutedims` in CUDA. I also find the pytorch code runs much faster on my V100 device, which is 
`0.18921153545379638`. Is it because I used the latest pytorch 1.10.1 ?

**Comment by GiggleLiu** [comment]
About @IvanYashchuk ’s question:
> Does CUDA.jl use caching allocator, does it need to call cudaMalloc for each new CuArray?

I have no idea, @maleadt do you know the answer and is it a key feature that can speed up the performance?

**Comment by maleadt** [comment]
> Does CUDA.jl use caching allocator, does it need to call cudaMalloc for each new CuArray?

If you're on a sufficiently new driver (11.2+), we rely on CUDA's memory pool functionality, which is essentially a caching allocator. It only re-uses data if you don't sync though, but that's something we could tune by setting CU_MEMPOOL_ATTR_RELEASE_THRESHOLD. To avoid GC pressure it still can be interesting to manually pre-allocate though.

**Comment by GiggleLiu** [comment]
@IvanYashchuk Another question related to your comment, do you know how to measure the time of permuting kernel in pytorch (e.g. making the array non-contiguous)? I want to know whether lazy permute can help in tensor networks (intuitively not, because the contraction is quite random).

To be specific, I do not know why the following code errors me

```julia
In [14]: import torch

In [15]: t = torch.zeros((2,)*28, device="cuda:0");

In [16]: timeit torch.reshape(t.permute(tuple(torch.randperm(28))), (2**13, 2**15)); torch.cuda.synchronize()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-16-744683736a27> in <module>
----> 1 get_ipython().run_line_magic('timeit', 'torch.reshape(t.permute(tuple(torch.randperm(28))), (2**13, 2**15)); torch.cuda.synchronize()')

~/miniconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2362                 kwargs['local_ns'] = self.get_local_scope(stack_depth)
   2363             with self.builtin_trap:
-> 2364                 result = fn(*args, **kwargs)
   2365             return result
   2366 

~/miniconda3/lib/python3.9/site-packages/decorator.py in fun(*args, **kw)
    230             if not kwsyntax:
    231                 args, kw = fix(args, kw, sig)
--> 232             return caller(func, *(extras + args), **kw)
    233     fun.__name__ = func.__name__
    234     fun.__doc__ = func.__doc__

~/miniconda3/lib/python3.9/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

~/miniconda3/lib/python3.9/site-packages/IPython/core/magics/execution.py in timeit(self, line, cell, local_ns)
   1178             for index in range(0, 10):
   1179                 number = 10 ** index
-> 1180                 time_number = timer.timeit(number)
   1181                 if time_number >= 0.2:
   1182                     break

~/miniconda3/lib/python3.9/site-packages/IPython/core/magics/execution.py in timeit(self, number)
    167         gc.disable()
    168         try:
--> 169             timing = self.inner(it, self.timer)
    170         finally:
    171             if gcold:

<magic-timeit> in inner(_it, _timer)

RuntimeError: tensor has too many (>25) dims
```

**Comment by GiggleLiu** [comment]
UPDATE: after grouping the indices, now the computing tiem of permutedims is reduced to ~50%.
![image](https://user-images.githubusercontent.com/6257240/148159546-e40ac7d5-bf68-47ca-9df7-646ce387c514.png)

But still not comparable to 2% in pytorch.

**Comment by IvanYashchuk** [comment]
The way you measure the performance of `permute` is fine. There's a restriction in PyTorch that Tensors on a CUDA device have a maximum allowed number of dimensions - 25.

**Comment by GiggleLiu** [comment]
After taking @maleadt 's advice in https://github.com/JuliaGPU/CUDA.jl/pull/1303#issuecomment-1005421244, I optimized the permutation kernel with the Int32 type, now the registers per thread reduced from 126 to 51 and the permutedims kernel speed up by 2x. I did the benchmark&profile again and it turns out the kernel performance of pytorch and CUDA+OMEinsum is close, the `volta_sgemm` kernel take 35% time in pytorch and 33.5% time in CUDA+OMEinsum. now I believe the permutation kernel performance is proper. However, `nsys` shows the program has a different bottleneck now, which I feel quite confused.
![image](https://user-images.githubusercontent.com/6257240/149223684-a5b32e6c-e2ba-4869-94dd-ae1f0817d5f0.png)

Anyone knows what are the `ioctl`s for?

**Comment by maleadt** [comment]
An `ioctl` is a generic mechanism to communicate with hardware. It can be anything. I only linked that to show that it can be CUDA related if it happens within specific API calls, but that doesn't look to be the case here. Try adding some NVTX markers to find out which operation is taking long (e.g. `NVTX.@range "synchronize" synchronize()` at the end instead of `CUDA.@sync`).

**Comment by GiggleLiu** [comment]
![image](https://user-images.githubusercontent.com/6257240/149337266-3754268b-7496-4801-8784-69952010c488.png)

@maleadt 
I just did the profiling again, added `NVTX.@range` for `permutedims` and `mm`, one see can the CUDA API call to `cuLaunchHostFunc` costs a lot of time. Do you know what is this function for?

**Comment by GiggleLiu** [comment]
![image](https://user-images.githubusercontent.com/6257240/149352344-ff10493c-821f-4ba7-91ce-fe546e7389f7.png)

It is much more clear now, `cuStreamSynchronize` is very slow.

**Comment by maleadt** [comment]
> It is indeed much more clear now, `cuStreamSynchronize` is very slow.

And that's what I was talking about in that forum post; what is `synchronize` doing here since the GPU is actually idle? As per that NVIDIA dev, it might be cleaning-up its memory pools, in which case the pool attribute to reserve memory might help. Did you try that out?

**Comment by GiggleLiu** [comment]
> As per that NVIDIA dev, it might be cleaning-up its memory pools, in which case the pool attribute to reserve memory might help. Did you try that out?

Wow, I added the following code at the top of the benchmark/profile file.
```julia
CUDA.attribute!(memory_pool(device()), CUDA.MEMPOOL_ATTR_RELEASE_THRESHOLD, typemax(UInt64))
```
It is faster than pytorch now (1.4s v.s. 1.7s in pytorch)! this is rediculus. Previously, I set this value to `UInt64(2*2^30)`, and this one did not work. I thought it will blow up my GPU memory if this value if too large, but it turns out not so. ❤️ @maleadt

**Comment by maleadt** [comment]
> BTW: Is it safe to set the default value of `MEMPOOL_ATTR_RELEASE_THRESHOLD` to `typemax(UInt64)` in CUDA.jl?

No, as that would interact badly with applications that allocate outside of the memory pool. I'm not even sure all NVIDIA's libraries use the memory pool by now...

**Comment by maleadt** [comment]
It'd be interesting to know what the working set size of this operation is, how much memory your GPU has, and how high of a value you actually need to reserve for it to perform well.

**Comment by GiggleLiu** [comment]
The GPU is: NVIDIA V100-SXM2 16G with NVIDIA Driver Version 470.63.01 and CUDA Version 11.4

I want to use up all the memory on a single card. The peak memory is bounded by `3G`. I am not sure how much to reserve for it perform well.

**Comment by GiggleLiu** [comment]
Thanks to the new pool management in CUDA, as well as a few optimization in the permutation function, we now have a very decent tensor network contraction performance in OMEinsum. So I will close this issue, thank you for your efforts @maleadt @Fanerst @IvanYashchuk, this is a community work!
