### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by lostella** [under-Peter/OMEinsum.jl#142]
If I go to the [stable documentation](https://under-peter.github.io/OMEinsum.jl/stable/) I see it is for `0.3.0`, but that seems from August 2021, `v0.6.12` being the latest one as of today.

**Comment by GiggleLiu** [comment]
Thanks for reporting the issue. The tagged version probably only update when the middle version number increase. I removed the stable doc badge from the readme for now to misdirect people to the wrong version.
Hopefully we can get it back in the next minor version release.

**Comment by GiggleLiu** [comment]
Fixed in #172
