### ISSUE TITLE
Warning during precompilation in OMEinsumContractionOrders package When insall this package.

### ISSUE THREAD

**Issue by zipeilee** [under-Peter/OMEinsum.jl#156]
Hi, I wanted to report a warning that I encountered while precompiling the OMEinsumContractionOrders package. During the precompilation process, I received the following warning message:

```
  7 dependencies successfully precompiled in 2 seconds. 187 already precompiled.
  1 dependency had warnings during precompilation:
┌ OMEinsumContractionOrders [6f22d1fd-8eed-4bb7-9776-e7d684900715]
│  WARNING: method definition for _convert at /home/xin/.julia/packages/OMEinsumContractionOrders/dbGto/src/json.jl:71 declares type variable LT but does not use it.
└
```

Although this warning does not seem to affect the functionality of the package, I wanted to bring it to your attention for further investigation and potential improvement.

Steps to reproduce:

Install the OMEinsum.jl package.

Precompile the package using Julia.

Expected behavior:
No warning messages should be displayed during the precompilation process.

Environment:

Julia version: v1.9.0
OMEinsumContractionOrders package version: v0.8.1
OMEinsum version: v0.7.4
Operating system: ArchLinux
Please let me know if you need any additional information or if there's anything else I can do to assist in resolving this issue!

**Comment by GiggleLiu** [comment]
Fixed in by a recent PR to OMEinsumContractionOrders.
