### ISSUE TITLE
Make einsum! inplace

### ISSUE THREAD

**Issue by GiggleLiu** [under-Peter/OMEinsum.jl#3]
e.g. In order to differentiate over trace `y = einsum("ii->", A)`, we can use the [index exchange AD rule](https://giggleliu.github.io/2019/04/02/einsumbp.html).
We get the backward function for adjoints `adjA = einsum("->ii", adjy)`.

This notation makes sense (it is broadcasting) except missing the shape information of output array.
One regards indices that does not appear in input as broadcasting indices.

If we have `einsum!("ii->", A, y)`, then the backward `einsum!("->ii", adjy, adjA)` is well defined. It is AD friendly to write inplace functions first.

How difficult it is to implement one in the branch `exp-space`? @under-Peter

**Comment by under-Peter** [comment]
Should be solved by e1903e1531672479a571484a48ec24635cca4346, although backwards probably doesn't work yet.

**Comment by GiggleLiu** [comment]
Good, BTW, is that branch ready to merge? I find it is still in `WIP` status.

**Comment by GiggleLiu** [comment]
Good, BTW, is that branch ready to merge? I find it is still in `WIP` status.

**Comment by under-Peter** [comment]
I want to add traces and partial-traces first. Probably just a pass before the existing `einsum`is called where all indices that are traces or partial traces are reduced - shouldn't be too hard (ingoring making it fast).
Then operations like "->ii" should be added and `exponential-space einsum`should have all the features we want and could be a reference for tests etc. Then we could merge to have a reference if that makes sense.

**Comment by GiggleLiu** [comment]
I wonder if iterating over all unique indices, cumulate products to output tensor would be simpler.

Using Cartesian indices
https://docs.julialang.org/en/v1/manual/arrays/index.html

Not sure the performance is good.
