### ISSUE TITLE
Why isn't the notatation for einsumopt the same as for einsum?

### ISSUE THREAD

**Issue by lgoncalves** [under-Peter/OMEinsum.jl#49]
The notation for einsumopt seems overly verbose, yet completely equivalent to that of einsum.  

It would be nice to have the same concise notation.

**Comment by GiggleLiu** [comment]
You are right. The same string literal notation will be added to `einsumopt`  soon.

**Comment by GiggleLiu** [comment]
`einsumopt` will be deprecated for the moment, since we have domain specific contraction order optimization in `TensorOperations` for pairwise contraction, which is used as the backend of `einsum`. For more sofisticated order optimization, we need treewidth, which would be considered in the future.
