### ISSUE TITLE
Using generated function without doing any calculation during type inference

### ISSUE THREAD

**Issue by Roger-luo** [under-Peter/OMEinsum.jl#52]
https://github.com/under-Peter/OMEinsum.jl/blob/08c6ba8138717516cf7ea760cb1cf8a7c1be5662/src/einsumopt.jl#L7

Why not just use a normal function here?

**Comment by GiggleLiu** [comment]
Ah, the optimalorder should be put outside the quote. However, your previous implementation reqires size information.

**Comment by GiggleLiu** [comment]
`einsumopt` will be deprecated, order optimization is automatically called when invoking pairwise contraction. For sofisticated order optimization, we need a tree width algorithm, which will be considered in the future.
