### ISSUE TITLE
List of testing cases

### ISSUE THREAD

**Issue by GiggleLiu** [under-Peter/OMEinsum.jl#6]
## A list of supported features
```julia
einsum!(((1, 1),), (M,), (), S)     # trace
einsum!(((1,2,2,1),), (F,), (), S)   # multiple trace
einsum!((1,2,2,3), (F,), (1,2,3), T)    # special diag
einsum!((1,2,2,3), (F,), (1,3), M)     # partial trace
einsum!(((1,2,3),(2,4,3)), (T1, T2), (1,4,3), T3)     # batched matmul

einsum!(((1,2), (1,3), (2,3,4)), (M1, M2, T), (1,4), M3)     # the AD of star contraction
einsum!(((1,2), (1,3), (1,4)), (M1, M2, M3), (2,3,4), T)     # the star contraction

einsum!(((),), S, (1,1), M)   # broadcasting  (required by AD)

#########  tested  #########
einsum!(((1,2),(2,3),(3,4)), (M1, M2, M3), (1,4), M4)     # matmul
einsum!(((1,2),(2,)), (M,V1), (1,), V2)      # matvec
einsum!(((1,2,3,4),), (F1,),(2,3,1,4), F2)      # permutation
einsum!(((1, 2), (1, 2)), (M1,  M1), (), S)    # norm 2
einsum!(((4,3,2,1), (2,3)), (F,M1),(1,4), M2)     # tensor contraction
einsum!(((1,2),(1,2),(1,3)), (M1,M2,M3), (3,), V)    # star and contract
einsum!(((1,2,3),),(T,),(1,2), M)     # index-sum
einsum!(((1,2),(1,2)), (M1,M2), (1,2), M3)     # Hadamard product
einsum!(((1,2),(3,4)),(M1,M2),(1,2,3,4),F)     # outer product
```
I summarized some of your tests, make them inplace, with last tensor as output.
Also, I added some new test cases, please include them in the tests.
Any important missing case?

Note:
Differentiating inplace operations would be dangerous,e.g.
```julia
x = f(y)  # note y is used to generare x
einsum!(((1,2),), x, (1,2) y)  # copy to itself
```

Since `y` is changed, `f` can not use the information in `y` for AD anymore.
A proper way is copying `y` when using `einsum!`, but we probably not doing so for performance consideration.

Maybe not importing `einsum!` to users would be a solution. Inside the code, it is gauranteed that `y` contains no information for AD.

**Comment by under-Peter** [comment]
I think batch-operations are missing from your list, otherwise it looks good.
Since `einsum` uses the in-place version under the hood I'm not sure whether testing `einsum!` explicitly is necessary, except for cases like backward-propagation where the output encodes the dimensionality (which we can't give to `einsum` right now).

**Comment by GiggleLiu** [comment]
Do you mean something like batched `matmul` ?
Testing `einsum` sounds good. Then just test broadcasting seperately.

**Comment by under-Peter** [comment]
Yes, like batched `matmul` since that's something e.g. `TensorOperations` lacks.
By broadcasting you mean?

**Comment by GiggleLiu** [comment]
Oh, sorry, I mean the [broadcasting in numpy](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html), which expands one dimension by copying elements.
"->ii", or "i->ij" like einsum are broadcasting, with new indices that appear in output tensor.
