### ISSUE TITLE
inplace interface

### ISSUE THREAD

**Issue by Roger-luo** [under-Peter/OMEinsum.jl#75]
I think it is useful to provide inplace einsum. especially in my case when I want to do some preallocations. It won't be differentiable at the moment however, but I think it is just fine.

**Comment by GiggleLiu** [comment]
We have a inplace fallback API `loop_einsum!`.
However, for the dispatched version, there is not an inplace version yet.

Do you think the inplace fallback would solve your problem?

**Comment by Roger-luo** [comment]
No, you need to dispatch them to specific rules as well. E.g ij,jk->ik should be dispatched to inplace mat mul, e.g mul!
