### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by under-Peter** [under-Peter/OMEinsum.jl#9]
We should keep a good overview of benchmarks of the different branches of `OMEinsum` as well as the alternatives from the python ecosystem. 
As a first attempt, I made a python benchmark-script [here](https://gist.github.com/under-Peter/a9fb5df9fece0bd36d29ee2c4cc0df28) which is for `numpy` but should be very easy to adapt to `pytorch` and somewhat easy to adapt to `tensorflow`. I'm not yet sure how to benchmark `tensorflow` since its execution-model, based on graphs and sessions, is opaque to me: are `constant`s evaluated beforehand? Does a session have overhead that could be avoided?

For julia, there's a suite in the branch #8 .
It would probably be best to evaluate all timings/data to `.json` files and plot/compare them with a script.

To do:
- [x] open repository for python benchmarks
- [x] use benchmark-suite in #1 
- [ ] write pytorch and tensorflow benchmarks
- [x] figure out whether `timeit` can decide itself how many samples to take in scripts just as in the REPL
- [x] run benchmarks for appropriate versions on some platform (cluster? laptop?)
- [x] export all results to `.json` (or alternative?) and compare/visualize

**Comment by Roger-luo** [comment]
As for benchmark, `PkgBenchmark` would be a nice tool for Julia while in python (for torch and tf) world you can use

https://github.com/ionelmc/pytest-benchmark

These tools are able to compare performance through commits and PRs and can generate a nice table

**Comment by GiggleLiu** [comment]
Thanks @Roger-luo !

**Comment by under-Peter** [comment]
Using `pytest-benchmark` and `PkgBenchmark`, I made a repository for the benchmarking-scripts and tools which you can find here: https://github.com/under-Peter/OMEinsum-Benchmarks
I have yet to write a benchmark for tensorflow (low priority) but the setup should allow to easily add benchmarks for different packages or branches. In `benchmarkdf.csv`, the `DataFrame` of results is loaded. Visualization is quick and dirty, can be improved if necessary.

**Comment by under-Peter** [comment]
Some insights from playing around with `numpy.einsum`:

###  No optimization
If one calls einsum with `np.einsum(...., optimize=False)` (default), it directly calls [this behemoth of a function](https://github.com/numpy/numpy/blob/b87bf343c2b1e6219300eaa645693c9dfff5e771/numpy/core/src/multiarray/einsum.c.src) which is called `c_einsum` in the python code. My understanding is that this calls a heavily optimized _loop-based_ einsum evaluator, similar to our `naive` approach or e.g. `Einsum.jl`.

This means it will have the same drawbacks as our naive loop-based approach: _Execution time scales exponentially in the number of indices_, simply because it loops over all possible indices.

So while for two-argument expressions it can be very fast, three-arguments already bring it to a crawl, see e.g.
```shell
$ python3 -m timeit -s "import numpy as np; a = np.random.rand(100,100)" 'np.einsum("ij,jk,kl -> il", a,a,a)'
10 loops, best of 3: 114 msec per loop

```
i.e. 114 ms for a simple multiplication of three matrices - compare with `a*a*a` in julia:  93.816 μs, a factor 1000 slower!
Thus `einsum` without optimisation is only usable for simple 2-argument expressions or small problems, where it shines. 

### Optimization
`np.einsum` has multiple options for optimization, which, as far as I understand, only affect how the optimal contraction is found. However it happens, a list of is returned with a sequence of contractions which are represented as einsum_strings.

E.g. `ij,jk,kl -> il` would be split into `ij,jk -> ik` and `ik,kl -> il`. These simpler strings are evaluated either by `tensordot` if possible (fast tensor contractions) or the `c_einsum` from above.
Since each intermediate operation has first to be decoded and called from python, this seems to have a significant overhead. For the simple example of multiplying three matrices, I find:
```bash
$ python3 -m timeit -s "import numpy as np; a = np.random.rand(100,100)" 'np.einsum("ij,jk,kl -> il", a,a,a,optimize="optimal")'
1000 loops, best of 3: 346 usec per loop
```
whereas in the dispatch-branch I get:
```julia
julia> @btime einsum((('i','j'),('j','k'),('k','l')), ($a, $a, $a), ('i','l'));
  121.028 μs (119 allocations: 160.05 KiB)
julia> @btime einsumopt((('i','j'),('j','k'),('k','l')), ($a, $a, $a), ('i','l'));
  193.401 μs (472 allocations: 250.59 KiB)
```
If we instead had a string-input to parse first that'd add another microsecond but nothing significant.

### Conclusion
If we add benchmarks for multiple-input expressions, we should start to see the drawbacks of `numpy.einsum` and see where our implementation really shines.
@GiggleLiu , agree?

**Comment by GiggleLiu** [comment]
After adding pytorch einsum benchmark on GPU, we can close this issue.
